### ISSUE TITLE
Update build dependencies in README

### ISSUE THREAD

**Issue by kdunn926** [inducer/pyopencl#102]
I know gcc-4.4.7 is quite old at this point, but it is the default for CentOS-6.6 - a quite common distro/release. I spent a fair bit of time debugging strange compiler error messages only to determine using >=gcc/g++-4.8.2 and binutils-2.23.52.0.1-10 from devtools-2 and OpenCL 1.2 headers were necessary to compile this on CentOS 6.6.

Would be great to mention the earliest known version of GCC/binutils/OpenCL API that will compile PyOpenCL successfully. 

Providing some sample error messages for search visibility:

Too old of a GCC version yields this:

```

/opt/centos/devtoolset-1.1/root/usr/bin/c++ -fno-strict-aliasing -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -O3 -DNDEBUG -fPIC -DPYGPU_PACKAGE=pyopencl -DPYGPU_PYOPENCL=1 -I/opt/intel/opencl/include -Isrc/c_wrapper/ -I/usr/include/python2.6 -c src/c_wrapper/wrap_cl.cpp -o build/temp.linux-x86_64-2.6/src/c_wrapper/wrap_cl.o -std=c++0x
In file included from src/c_wrapper/clhelper.h:1:0,
                 from src/c_wrapper/wrap_cl.cpp:2:
src/c_wrapper/error.h:195:37: error: ‘ArgPack<CLArg, Types ...>::ArgPack’ names constructor
In file included from src/c_wrapper/wrap_cl.cpp:3:0:
src/c_wrapper/platform.h:17:18: error: ‘clobj<_cl_platform_id*>::clobj’ names constructor
In file included from src/c_wrapper/wrap_cl.cpp:4:0:
src/c_wrapper/device.h:48:5: error: looser throw specifier for ‘virtual device::~device()’
In file included from src/c_wrapper/error.h:3:0,
                 from src/c_wrapper/clhelper.h:1,
                 from src/c_wrapper/wrap_cl.cpp:2:
src/c_wrapper/clobj.h:25:7: error:   overriding ‘virtual clobj<_cl_device_id*>::~clobj() noexcept (true)’

```

Too new of OpenCL headers (2.0, 2.1) yield this:

```

In file included from src/c_wrapper/memory_object.h:1:0,
                 from src/c_wrapper/memory_object.cpp:1:
src/c_wrapper/error.h: In instantiation of ‘void call_guarded(cl_int (*)(ArgTypes ...), const char*, ArgTypes2&& ...) [with ArgTypes2 = {const memory_object* const&, unsigned int&, ArgBuffer<unsigned int, (ArgType)1>, std::nullptr_t}; ArgTypes = {_cl_mem*, unsigned int, long unsigned int, void*, long unsigned int*}; cl_int = int]’:
src/c_wrapper/clhelper.h:177:63:   required from ‘generic_info get_int_info(cl_int (*)(ArgTypes ...), const char*, const char*, ArgTypes2&& ...) [with T = unsigned int; ArgTypes = {_cl_mem*, unsigned int, long unsigned int, void*, long unsigned int*}; ArgTypes2 = {const memory_object* const, unsigned int&}; cl_int = int]’
src/c_wrapper/memory_object.cpp:54:16:   required from here
src/c_wrapper/error.h:233:51: error: no matching function for call to ‘CLArgPack<const memory_object* const, unsigned int, ArgBuffer<unsigned int, (ArgType)1>, std::nullptr_t>::clcall(cl_int (*&)(_cl_mem*, unsigned int, long unsigned int, void*, long unsigned int*), const char*&)’
     cl_int status_code = argpack.clcall(func, name);
                                                   ^

```

**Comment by inducer** [comment]
Thanks for reporting back on this! As you can see above, I've added a section to the README to give some visibility to what you found.

I routinely build with the 2.0 CL headers and have never had a problem. Are the issues you found with new CL headers specific to old GCCs in your experience?

**Comment by kdunn926** [comment]
I'll check on the OpenCL headers with that compiler version to be sure.

**Comment by inducer** [comment]
Closing for lack of activity and clear reproducible bug. Reopen if this is still an issue.
