### PR TITLE
Fix build on macos X

### LINKED ISSUE #422: Failed to build pyopencl 2021.1 from source on macos X
Adding `"-arch", "arm64"` cxx flags (PR #405) makes build fail on macos X with errors like:
```
     In file included from src/wrap_constants.cpp:30:
    In file included from src/wrap_cl.hpp:54:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenCL.framework/Headers/opencl.h:12:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenCL.framework/Headers/cl.h:28:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenCL.framework/Headers/cl_platform.h:213:
    In file included from /Applications/Xcode_12.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdint.h:123:
    In file included from /Applications/Xcode_12.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include/stdint.h:52:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdint.h:53:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types/_intptr_t.h:30:
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/types.h:37:2: error: architecture not supported
    #error architecture not supported
```

### PR DESCRIPTION
**Pull request by t20100**
This PR proposes a fix for building pyopencl on macos 10

It also fixes a typo on string quotes introduced in https://github.com/inducer/pyopencl/commit/3823b9ff6ab1c8ad9233cb3e380ddf3e2d8adbe0

I tested it on macos 10.12, but I can't test it on macos 11...

closes #422

### CODE REVIEW

**Comment by inducer** [comment]
Thanks!

https://gitlab.tiker.net/inducer/pyopencl/-/merge_requests/135

**Comment by isuruf** [comment]
Should we just remove all the `-arch` flags?

**Comment by inducer** [comment]
Not opposed, maybe that's better.

**Comment by inducer** [comment]
I've canceled the automerge on Gitlab while we discuss.

**Comment by t20100** [comment]
Updated to remove the `-arch` flags instead.

On macos 10, it makes no difference since the quote typo `"-arch', 'i386"` was preventing the `-arch i386` to be taken into account.
Same as before, it not tested on macos 11.

**Comment by inducer** [comment]
Thanks! This will merge once the Gitlab build completes.

**Comment by jccurtis** [comment]
Thanks for this everyone! Is there a planned version bump for pypi?

**Comment by inducer** [comment]
Pushed out 2021.1.1 just now.

**Comment by t20100** [comment]
Great, thanks for the reactivity!
