### ISSUE TITLE
AttributeError: cdata 'generic_info *' has no field 'free_type' -- on context/platform instantion

### ISSUE THREAD

**Issue by skyreflectedinmirrors** [inducer/pyopencl#205]
I'm using python3.4.2, on version 2017.2 while a python2.7.5 version of `pyopencl` on the same box works as expected:

```
import pyopencl as cl
cl.create_some_context()

Choose platform:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ncurtis/.local/lib/python3.4/site-packages/pyopencl/__init__.py", line 599, in create_some_context
    cc_print("[%d] %s" % (i, pf))
  File "/home/ncurtis/.local/lib/python3.4/site-packages/pyopencl/cffi_cl.py", line 667, in __repr__
    return "<pyopencl.Platform '%s' at 0x%x>" % (self.name, self.int_ptr)
  File "/home/ncurtis/.local/lib/python3.4/site-packages/pyopencl/cffi_cl.py", line 2880, in result
    return info_method(self, info_attr)
  File "/home/ncurtis/.local/lib/python3.4/site-packages/pyopencl/cffi_cl.py", line 259, in get_info
    return _generic_info_to_python(info)
  File "/home/ncurtis/.local/lib/python3.4/site-packages/pyopencl/cffi_cl.py", line 148, in _generic_info_to_python
    if info.free_type:
AttributeError: cdata 'generic_info *' has no field 'free_type'
```

Output of various pip freeze that may be relevant:
```pip3.4 freeze

cffi==1.11.2
cgen==2017.1
codepy==2017.2
colorama==0.3.9
Cython==0.26.1
genpy==2016.1.3
islpy==2016.2.2
loo.py==2017.1
Mako==1.0.7
numpy==1.13.3
pymbolic==2017.1
pyopencl==2017.2
pytest==3.2.3
pytools==2017.6
```

Any thoughts on why this is happening?  It just popped up after I upgraded from 2016.2

**Comment by inducer** [comment]
This looks like the cffi used for building doesn't match the cffi version installed at runtime. Did you recently `rm -Rf build` and then reinstall pyopencl?

**Comment by skyreflectedinmirrors** [comment]
Hmm, I was building using `pip3.4 install . --user`, which places the build path.... somewhere?
Seems to have been the issue though, as installing via `python3.4 setup.py install --user` fixed it
